// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ExpenseFormController from "./expense_form_controller"
application.register("expense-form", ExpenseFormController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import WizardController from "./wizard_controller"
application.register("wizard", WizardController)
