default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: splitwise_dev
  host: localhost

development:
  <<: *default
  database: splitwise_development

test:
  <<: *default
  database: splitwise_test

production:
  <<: *default
  database: splitwise_production
  username: <%= ENV["SPLITWISE_DATABASE_USERNAME"] %>
  password: <%= ENV["SPLITWISE_DATABASE_PASSWORD"] %>
  host: <%= ENV["SPLITWISE_DATABASE_HOST"] %>